FROM python:3.10

ENV PYTHONUNBUFFERED=1

COPY --from=ghcr.io/astral-sh/uv:0.9.26 /uv /uvx /bin/

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy

WORKDIR /app/

ENV PATH="/app/.venv/bin:$PATH"

COPY pyproject.toml ./
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --no-install-workspace

COPY . /app/

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync

CMD ["bash", "-c", "python app/backend_pre_start.py && alembic upgrade head && python app/initial_data.py && fastapi dev --host 0.0.0.0 --port 8000 app/main.py"]
